CREATE DATABASE CATALOGO_M;
GO

USE CATALOGO_M;
GO 

CREATE TABLE GENERO (
    idGenero TINYINT  PRIMARY KEY IDENTITY(1,1),
	nomeGenero VARCHAR(30)
);
GO

CREATE TABLE FILME (
   idFilme SMALLINT PRIMARY KEY IDENTITY(1,1),
   idGenero TINYINT FOREIGN KEY REFERENCES GENERO(idGenero),
   tituloFilme VARCHAR(70)
);
GO 