CREATE DATABASE Exercicio_Pessoas; 

USE Exercicio_Pessoas; 

CREATE TABLE PESSOA(
  idPessoa INT PRIMARY KEY IDENTITY(1,1),
  nomePessoa VARCHAR(20) UNIQUE,
  CNH VARCHAR(10)
);

CREATE TABLE TELEFONE(
  idTelefone INT PRIMARY KEY IDENTITY(1,1),
  idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
  numeroTelefone CHAR(11) 
);

CREATE TABLE EMAIL(
  idEmail INT PRIMARY KEY IDENTITY(1,1),
  idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
  end_email VARCHAR(256) UNIQUE
);