CREATE DATABASE Veiculos;

USE Veiculos;

CREATE TABLE EMPRESAS
(
    IdEmpresa   INT PRIMARY KEY IDENTITY,
    nomeEmpresa       VARCHAR(200) NOT NULL
);

CREATE TABLE MARCAS
(
    IdMarca		INT PRIMARY KEY IDENTITY,
    nomeMarca		VARCHAR(200)
);

CREATE TABLE MODELOS
(
    IdModelo	INT PRIMARY KEY IDENTITY,
    Descricao  VARCHAR(200),
);

CREATE TABLE VEICULOS
(
    IdVeiculo   INT PRIMARY KEY IDENTITY,
    IdModelo   INT FOREIGN KEY REFERENCES MODELOS (IdModelo),
	IdMarca		INT FOREIGN KEY REFERENCES MARCAS (IdMarca),
    Placa	    VARCHAR(200) UNIQUE,
	IdEmpresa	INT FOREIGN KEY REFERENCES EMPRESAS (IdEmpresa)
);

CREATE TABLE CLIENTES
(
    IdCliente   INT PRIMARY KEY IDENTITY,
    Nome	    VARCHAR(200),
	CPF		VARCHAR(200)
);

CREATE TABLE ALUGUEIS
(
    IdAluguel   INT PRIMARY KEY IDENTITY,
    IdCliente	INT FOREIGN KEY REFERENCES CLIENTES (IdCliente),
	IdVeiculo	INT FOREIGN KEY REFERENCES VEICULOS (IdVeiculo),
	DataInicio DATE NOT NULL,
	DataFim	DATE NOT NULL
);