USE CATALOGO_M;

INSERT INTO GENERO (nomeGenero)
VALUES ('TERROR'), ('AÇÃO');


INSERT INTO GENERO (nomeGenero)
VALUES ('COMÉDIA');



INSERT INTO FILME (idGenero,tituloFilme)
VALUES (2,'INDIANA JONES'), (1,'INVOCAÇÃO DO MAL'),
       (1,'O EXORCISTA'), (3,'A CULPA É DAS ESTRELAS');


UPDATE FILME  
SET tituloFilme = 'OS FAROFEIROS'
WHERE idFilme = 4; 